# Prometheus Configuration for Tauri Desktop Application Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'free-deep-research-tauri'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Tauri Application Metrics (if exposed)
  - job_name: 'tauri-app'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Tauri app running on host
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis Metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom Application Metrics
  - job_name: 'fdr-custom-metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']  # Custom metrics endpoint
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s

# Remote write configuration (for external monitoring services)
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 7d
    retention.size: 1GB
    wal-compression: true
