[package]
name = "free-deep-research-system"
version = "3.0.0"
description = "Free Deep Research System - Core Library (Test Configuration)"
authors = ["Free Deep Research Team"]
license = "MIT"
repository = "https://github.com/free-deep-research/system"
edition = "2021"

[lib]
name = "free_deep_research_system"
crate-type = ["lib"]

# Remove build script for library-only testing
# build = "build.rs"

[dependencies]
# Core dependencies only (no GUI)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"

# HTTP client and networking
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
url = "2.5"

# Database
rusqlite = { version = "0.30", features = ["bundled", "chrono"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Date and time
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.6", features = ["v4", "serde"] }

# Utilities
once_cell = "1.20"
parking_lot = "0.12"
base64 = "0.22"
dirs = "5.0"
sysinfo = "0.30"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Configuration
config = "0.14"
toml = "0.8"

# Regex
regex = "1.10"

# URL encoding for research queries
urlencoding = "2.1"

# Random number generation
rand = "0.8"

# Binary serialization
bincode = "1.3"

# Template engine
tera = "1.19"

# PDF generation
wkhtmltopdf = "0.4"

# Encryption and security
ring = "0.17"
aes-gcm = "0.10"
x25519-dalek = "2.0"

# Rate limiting
governor = "0.6"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
mockall = "0.12"

[[test]]
name = "phase1_verification"
path = "tests/phase1_verification.rs"

[features]
default = []
test-mode = []
